deploy:
  needs: [build]
  runs-on: ubuntu-latest

  steps:
    - name: SSH deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
          . ~/.nvm/nvm.sh

          nvm install ${{ github.event.inputs.node-version }} # Use the input parameter for node version
          npm install -g pm2
          cd ~/CICD
          git pull origin main
          npm install
          npm run build
          pm2 restart api
